# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BookSearch' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BookSearch

  pod 'RxSwift', '~> 5.0'
  pod 'RxCocoa', '~> 5.0'
  pod 'RealmSwift', '5.0.0-beta.1'
  pod 'Kingfisher', '~> 5.12'
  
end
